# Generated by Django 3.2.7 on 2021-09-16 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_deposit_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moneytransfer',
            old_name='enter_the_amount_to_be_transferred_in_INR',
            new_name='enter_the_amount_to_be_transferred_in_Npr',
        ),
    ]
