# Generated by Django 3.2.7 on 2021-09-18 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0004_alter_basicdetails_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicdetails',
            name='profile_pic',
            field=models.FileField(default='static/images/default_user.png', upload_to='static/photo'),
        ),
        migrations.AddField(
            model_name='basicdetails',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
