# Generated by Django 3.2.7 on 2021-09-20 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20210918_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicdetails',
            name='DOB',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='basicdetails',
            name='annual_income',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='basicdetails',
            name='email',
            field=models.EmailField(default=None, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='basicdetails',
            name='mobile',
            field=models.CharField(default=0, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='basicdetails',
            name='name',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='basicdetails',
            name='occupation',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='basicdetails',
            name='profile_pic',
            field=models.FileField(default='static/images/default_user.png', null=True, upload_to='static/photo'),
        ),
        migrations.AlterField(
            model_name='basicdetails',
            name='sex',
            field=models.CharField(default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='basicdetails',
            name='user_name',
            field=models.CharField(default=None, max_length=150, null=True),
        ),
    ]
