# Generated by Django 3.2.7 on 2021-09-20 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20210920_1301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='enter_the_amount_to_be_transferred_in_Npr',
            new_name='enter_the_amount_you_want_in_Npr',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='enter_the_your_account_number',
            new_name='enter_your_account_number',
        ),
    ]
