# Generated by Django 3.2.7 on 2021-09-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20210920_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicdetails',
            name='email',
            field=models.EmailField(default=None, max_length=254, null=True, unique=True),
        ),
    ]
